### ISSUE TITLE
Maven Plugin Report Phase Failure

### ISSUE THREAD

**Issue by kaiyuanw** [GZoltar/gzoltar#1]
### Context
GZoltar's report phase fails when using the maven plugin

### Steps to Reproduce
1. Run `git clone https://github.com/kaiyuanw/GZoltar-Bug-Report`
2. Run `cd GZoltar-Bug-Report && mvn test -Pgzoltar`
3. You will see report failure similar to the log file at https://github.com/kaiyuanw/GZoltar-Bug-Report/blob/master/gzoltar.log

### Environment (please complete the following information, if relevant):
 - OS: Ubuntu
 - Version 16.04

### Additional comments
*Please let me know if the failure is because of the way I set up the pom.xml file.*

**Comment by jose** [comment]
Hi @kaiyuanw,

First of all thank you for reporting this issue. This issue turned out to be related to a bug in the underline bytecode toolkit used by GZoltar and not to GZoltar itself. I've just upgraded javassist to v3.23.1-GA and everything seems to be working just fine.

As I'm not planning to release a new version of GZoltar soon, in order to use the latest version you must:
```
# Clone GZoltar repository
$ git clone https://github.com/GZoltar/gzoltar.git
$ cd gzoltar
# Install the latest version
$ mvn --projects '!com.gzoltar.test' install -DskipTests=true
```
Assuming everything goes well, you will then need to change [line 826 of your pom.xml](https://github.com/kaiyuanw/GZoltar-Bug-Report/blob/master/pom.xml#L826) to `<version>1.7.1-SNAPSHOT</version>`.

Please let me know if my "[fix](https://github.com/GZoltar/gzoltar/commit/181323106ae8bcd2b3a8e6be3a2c3c1f56fe1da8)" does not work for you.

--
Best,
Jose

**Comment by kaiyuanw** [comment]
Thank you so much for the timely reply!  It seems the problem is also solved on my machine.

Thank you again!

**Comment by kaiyuanw** [comment]
GZoltar's maven plugin still fails for another project.  See issue https://github.com/GZoltar/gzoltar/issues/2
