### ISSUE TITLE
[Eclipse Plugin] No regression testing running and no data generated

### ISSUE THREAD

**Issue by zhangysh1995** [GZoltar/gzoltar#11]
### Context
Eclipse plugin doesn't generate any data or show the visualization.

### Steps to Reproduce
1. Use Eclipse 2018-12
2. Use evosuite to generate test cases
3. Use plugin to do fault-localization

### GZoltar arguments
Eclipse plugin, default settings

### Expected behaviour
It should show the regression testing results, and also show the ranking of all lines.

### Environment (please complete the following information, if relevant):
 - OS: MacOS 
 - Version: 10.14.3

````
○ → java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
````

### Additional comments
Regression Testing Panel is empty and Diagnostic Report is all green (there are failed test cases).

**Comment by jose** [comment]
Hi @zhangysh1995,

The [GZoltar Eclipse plugin](http://www.gzoltar.com/eclipse-plugin.html) is still an experimental project and it has not been updated since it was released. Are you interested in any particular feature of the GZoltar Eclipse plugin? Does your setup require the use of Eclipse to perform fault localization? If the answer is no, I would recommend you use one of the many GZoltar plugins to perform fault localization.


--
Best,
Jose

**Comment by zhangysh1995** [comment]
@jose I used Gzoltar for a course assignment and finally I could run it with the `Maven` plugin. Thanks for your reply. I close this issue.
