### ISSUE TITLE
how to activate prioritization of Junit test cases with the maven plugin?

### ISSUE THREAD

**Issue by Mishabuzov** [GZoltar/gzoltar#17]
Hello, recently I have read your article "GZoltar: An Eclipse Plug-In for Testing and Debugging", where it is mentioned that it is possible to use GZoltar for prioritization and minimization of the Junit test cases. So, I was inspired!
I have successfully run the [maven example](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples), but unfortunately, I have not found any prioritization reports. I mean that I expect something more useful than just prioritization by runtime (which is produced in the tests.csv), and I want concretely prioritization of test cases, not fault localization reports.
So my question is it really possible to prioritize (or at least minimize) Junit test cases with GZoltar, and if it is possible, how to do it? How to configure GZoltar maven plugin for that purpose?

Please, help me :)
I really want to find a useful Junit test case prioritization tool.

**Comment by jose** [comment]
Hi @Mishabuzov,

Thanks for your interest in the GZoltar library.

GZoltar has suffered a massive refactor since we published it at ASE2012 and the prioritization module is no longer available.  That module was not stable enough and at some point we decided to not include it. We still hope to integrate it again soon.

If you are still looking for a test prioritization tool I would recommend [Kanonizo](https://github.com/kanonizo/kanonizo). Kanonizo supports the GZoltar's prioritization algorithm previously published in our [ASE2012 paper](https://jose.github.io/assets/pdfs/ASE2012-paper.pdf) and also described in [here](https://jose.github.io/assets/pdfs/TSE-TH2013-paper.pdf).


--
Best,
Jose
