### ISSUE TITLE
Maven Plugin Report Phase Failure Again

### ISSUE THREAD

**Issue by kaiyuanw** [GZoltar/gzoltar#2]
### Context
GZoltar's report phase fails when using the maven plugin

### Steps to Reproduce
1. Run `git clone https://github.com/kaiyuanw/GZoltar-Bug-Report`
2. Run `cd GZoltar-Bug-Report && mvn test -Pgzoltar`
3. You will see report failure similar to the log file at https://github.com/kaiyuanw/GZoltar-Bug-Report/blob/master/commons-math.log

### Environment (please complete the following information, if relevant):
 - OS: Ubuntu
 - Version 16.04

### Additional comments
*GZoltar now works for commons-lang but does not work for commons-math.  Could you please let me know how to fix that?*

**Comment by jose** [comment]
Hi @kaiyuanw,

Thanks for reporting this issue.

Just a bit of a context before explaining how to address this issue. In order to keep a minimal runtime-overhead and small *.ser files even for very large applications under test, GZoltar (as other tools like for example JaCoCo) uses a _class id_ (which is the md5 hash of the bytecode of each class) rather than the name to unambiguously identify Java classes. Thus, at runtime, data is sampled and stored to *.ser files; at analysis time, the _class ids_ are used to relate analysed classes with the execution data. The main disadvantage of using _class ids_ is that a byte-to-byte mismatch can occur when different classes are used at runtime and at analysis time. This could be due to several reasons: different compilers, mocking frameworks, when another Java agent is configured before the GZoltar agent, etc.

In your project, at runtime, classes are first instrumented by the JaCoCo agent and only then by the GZoltar agent. I.e., at runtime, GZoltar does not _see_ the original bytecode but an already modified bytecode and therefore does not compute a _class id_ that represents the original bytecode. Because at analysis time classes are only instrumented by GZoltar (the jacoco profile in your project does not get activated), the bytecode of each class and therefore its _class id_ is not the same as at runtime. Thus, due to this mismatch, GZoltar is not able to analyse the coverage of each class because it cannot relate the execution data to any class.

Although there are several workarounds to address this issue like performing offline instrumentation before running any test case, etc, I would recommend to just disable the jacoco profile by running:
```
$ mvn clean test -Pgzoltar -P!jacoco
```
this way, the only Java agent on the classpath would be the GZoltar agent and therefore each class will not be instrumented by any other agent/tool except GZoltar.


--
Best,
Jose

**Comment by kaiyuanw** [comment]
Thanks, Jose.  That solution works for me.  BTW, does GZoltar maven plugin supports maven project with multiple modules?

**Comment by jose** [comment]
> Thanks, Jose. That solution works for me.

Great.

> Does GZoltar maven plugin supports maven project with multiple modules?

No, it does not support. GZoltar maven plugin only works on single modules, i.e., tests are executed within the module and fault-localization reports are created for each module separately. It's indeed an interesting feature and I will definitely implement it in the future.
