### ISSUE TITLE
Question about the Fault Localization results

### ISSUE THREAD

**Issue by goodtaeeun** [GZoltar/gzoltar#20]
Hello,
I am trying to use GZoltar framework as a fault localization tool to implement a Automatic Program Repair project with genetic programming algorithms. 
I used the "run.sh" file in the gzoltar/com.gzoltar.cli.examples, modified it a little for some file paths, but not too much. 

When tested with the given example source and test codes, it produced the csv file "ochiai.ranking.csv" as one of its result. It is the file that contains an ordered list of suspicious points(class name, method, line numbers) with its suspicious score.

However, I found that the methods and lines in the test code were also found in the result. Result was similar when I tested it on one of the dataset from the defect4java, Math-280. Test methods in the test files and test methods were on the list of suspicious points in "ochiai.ranking.csv". 

It was hard for me to intuitively understand the reason. Isn't the fault localization supposed to point out the faulty part in the actual source code? not the test code? So if this result is intended or there is no problem with it, could you please address the reason for me?
Should I just leave out the lines from the test codes when targeting the faulty lines?

**This is top few lines of the "ochiai.ranking.csv" resulted from testing with Math-280. We can see that the high scored lines are from the test files.
![image](https://user-images.githubusercontent.com/57384091/78566349-0a18ab00-785a-11ea-9db0-492b81be6512.png)

[ochiai.ranking.txt](https://github.com/GZoltar/gzoltar/files/4438788/ochiai.ranking.txt)

Regards,
Kim.

**Comment by jose** [comment]
Hi @goodtaeeun,

If no pattern is specified, GZoltar instruments **all** classes that are loaded by JVM.  In the cli.example you mentioned, GZoltar only instruments `org.gzoltar.examples.CharacterCounter` (as specified by the ['includes' parameter](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L121)) and therefore no line or method of any other class is reported.  Here is the content of the `ochiai.ranking.csv` file generated by the [run.sh script](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L121) in the cli.example module.
```
$ cat build/sfl/txt/ochiai.ranking.csv
name;suspiciousness_value
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):39;1.0
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):38;0.8164965809277261
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):40;0.8164965809277261
org.gzoltar.examples$CharacterCounter#CharacterCounter():30;0.7559289460184544
org.gzoltar.examples$CharacterCounter#CharacterCounter():31;0.7559289460184544
org.gzoltar.examples$CharacterCounter#CharacterCounter():32;0.7559289460184544
org.gzoltar.examples$CharacterCounter#CharacterCounter():33;0.7559289460184544
org.gzoltar.examples$CharacterCounter#CharacterCounter():34;0.7559289460184544
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):37;0.7559289460184544
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):48;0.7559289460184544
org.gzoltar.examples$CharacterCounter#getNumLetters():51;0.7559289460184544
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):43;0.75
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):42;0.6708203932499369
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):41;0.5773502691896258
org.gzoltar.examples$CharacterCounter#processString(java.lang.String):45;0.0
org.gzoltar.examples$CharacterCounter#getNumDigits():55;0.0
org.gzoltar.examples$CharacterCounter#getNumOtherCharacters():59;0.0
```

There are two ways to exclude test classes from ending up in the fault localization report.

**Option 1:** Set the ['includes' parameter](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L121)) with the canonical name of classes you want to **include** in the fault localization report, e.g., the canonical name of non-test classes.

**Option 2:** Set the ['excludes' parameter](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L121)) with the canonical name of classes you want to **exclude** in the fault localization report, e.g., the canonical name of test classes.

Note: the 'includes' and 'excludes' parameters support regex expressions. For instance:
```
includes="org.foo.*"
```
makes GZoltar instrument all classes in the package `org.foo`.
```
includes="org.foo.Bar*"
```
makes GZoltar instrument all classes in the package `org.foo` and that are named as, e.g., `BarOne`, `BarOther`, etc.

The 'excludes' parameter supports the exact same expressions as the 'includes' parameter but instead of considering the classes, it excludes them.


--
Best,
Jose

**Comment by goodtaeeun** [comment]
First of all, Thank you for your sincere reply.

However, I was considering and trying only the offline instrumentation.
The solution you suggested seems to only apply to online instrumentation.
I could't find include/exclude options in the offline instrument phase.

Would there be a way to exclude the test files in the offline instrumentation?
If there isn't, I might just switch to online instrumentation only.

Regards,
Kim.

**Comment by jose** [comment]
Hi @goodtaeeun,

> However, I was considering and trying only the offline instrumentation. The solution you suggested seems to only apply to online instrumentation.

I'm sorry I was not aware of that.

> Would there be a way to exclude the test files in the offline instrumentation?

Yes, I've just added another parameter to the `faultLocalizationReport` command so that you can exclude the test classes from appearing in the fault localization report.

In the command to [generate the fault localization report](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L169), set the parameter `--include` as I previously explained. For example, `--includes "org.foo.*"` will make GZoltar to generate a fault localization report with all classes in the package `org.foo` but no other class. Or, for your particular case, set the parameter `--excludes` as `--excludes "*Test"` to exclude all class names that end with "Test" (in theory, this should catch all your test classes) from appearing in the fault localization report.

I hope this helps.

--
Best,
Jose
