### ISSUE TITLE
Missing images in https://marketplace.visualstudio.com/items?itemName=GZoltar.vscode-gzoltar

### ISSUE THREAD

**Issue by jose** [GZoltar/gzoltar#38]
Hi @Klaysb,

I've recently published a new version of the GZoltar's Visual Studio Code extension and the images in the README file do not show up in https://marketplace.visualstudio.com/items?itemName=GZoltar.vscode-gzoltar.  Any clue on why?

--
Best,
Jose

**Comment by Klaysb** [comment]
Hello,

That's because when publishing the extension's README in the marketplace, the image URLs need to resolve to https URLs. However, in the GZoltar repository they only contain the partial path (i.e., `resources/docs/remote-dev-status-bar.png` when it should be `https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.vscode/resources/docs/remote-dev-status-bar.png?raw=true`).

**Comment by jose** [comment]
Got it.  Thanks.
