### ISSUE TITLE
A query about Gzoltar

### ISSUE THREAD

**Issue by Kaka727** [GZoltar/gzoltar#4]
It is not a bug report, In fact, it is like a query.
I note that the developers have stated that we can call Gzoltar's service by the command like "java -jar gzoltarcli.jar".
I'd like to know shall we install GZoltar locally before using this command. I believe this step is needed since nullpointerException will occur if not. But what packages or libraries should we install? It is not clear in the README file.

Thanks~

**Comment by jose** [comment]
Hi @Kaka727,

> I note that the developers have stated that we can call Gzoltar's service by the command like "java -jar gzoltarcli.jar".

True for all releases before version 1.7.0. Since version 1.7.0, it is recommended to use GZoltar's [Ant](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.ant) or [Maven](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven) plugin to perform fault localization. In this repository you can find examples how to integrate GZoltar in your build system, e.g., an Ant project example can be find in [here](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.ant.examples/simple) and a Maven project example can be find in [here](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples/simple).

PS: I noticed you have been reporting issues in the [Defects4J repositoy](https://github.com/rjust/defects4j) as well. In case you are planning to use GZoltar to perform fault localization on Defects4J bugs, I would recommend you to use my Defects4J [fork](https://github.com/jose/defects4j) (in particular the `fault-localization` branch). I have integrated GZoltar in Defects4J so that people could easily perform localization for any Defects4J bug, for example:
```bash
# Perform fault localization for project Chart, bug id 1
mkdir /tmp/Chart-1b
$D4J_HOME/framework/bin/defects4j checkout -p Chart -v 1b -w /tmp/Chart-1b
$D4J_HOME/framework/bin/defects4j fault-localization -w /tmp/Chart-1b
```


--
Best,
Jose

**Comment by Ahmedfir** [comment]
I know that this question has already been closed, more than 2 years ago.
But I couldn't run Gzoltar from defects4J via the command that you mentioned in your comment:
`$D4J_HOME/framework/bin/defects4j fault-localization -w /tmp/Chart-1b`
Is this command still implemented in the current version of defects4j or should I run it differently?

**Comment by jose** [comment]
Hi @Ahmedfir,

The `fault-localization` command is only available on [my Defects4J fork](https://github.com/jose/defects4j) in the [fault-localization branch](https://github.com/jose/defects4j/tree/fault-localization).  Are you using my fork of the Defects4J framework?


--
Best,
Jose

**Comment by Ahmedfir** [comment]
Hi @jose,

Thanks for the quick answer. No, I am not using that fork. :p :D  
I will try it.  

Cheers,
Ahmed

**Comment by Ahmedfir** [comment]
Hi @jose,

I am now using the right fork and branch of defects4j. 
I have a question about how to run all tests of the test suite and not only the ones that are relevant (as described in the documentation)?

I have checked the documentation in `FaultLocalization.pm` and in `run_fault_localization.pl` and I didn't find any way to run Gzoltar (of the defects4j fork) on all the tests of the test suite.
I have already tried the available parameter options (which seem to work fine): 

- `-a` or nothing: to run only the relevant tests written by the developer and
- `-t` <class::test>: to run one single test.

Do you know how can I run the whole test suite? 

Many thanks again!
Ahmed

**Comment by jose** [comment]
Hi @Ahmedfir,

> how to run all tests of the test suite and not only the ones that are relevant (as described in the documentation)?

I was under the impression that `-a` would run all tests in a given project, but it does not seem to be the case.  Problem seems to be in [here (438-447)](https://github.com/jose/defects4j/blob/fault-localization/framework/projects/defects4j.build.xml#L438) which is either expecting for a test class or all relevant tests of a given project/bug.  The easiest, **non official**, way is to address your case is to manually replace [this line](https://github.com/jose/defects4j/blob/fault-localization/framework/projects/defects4j.build.xml#L462)
```xml
            <arg value="${rel.tests.expr}" />
```
with
```xml
            <arg value="*" />
```
whenever you indeed need to run all tests.


--
Best,
Jose
