### ISSUE TITLE
How can I get the lines that were covered by tests? 

### ISSUE THREAD

**Issue by nakhlarafi** [GZoltar/gzoltar#60]
Hello there, Is there any way to get all the lines that were covered by a test case using gzoltar? I was searching for something like this below. So this is a test method from defects4j Lang47B. I want to know the lines it covered. 

org.apache.commons.lang.text.StrBuilderTest.testLang412Right(org.apache.commons.lang.text.StrBuilderTest)	org.apache.commons.lang.text.StrBuilder:ensureCapacity:233	org.apache.commons.lang.text.StrBuilder:getNullText:158	org.apache.commons.lang.text.StrBuilder:<init>:98	org.apache.commons.lang.text.StrBuilder:<init>:99	org.apache.commons.lang.text.StrBuilderTest:testLang412Right:1737	org.apache.commons.lang.text.StrBuilderTest:testLang412Right:1736	org.apache.commons.lang.text.StrBuilderTest:testLang412Right:1735	org.apache.commons.lang.text.StrBuilderTest:testLang412Right:1734	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1229	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1231	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1230	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1229	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1228	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1227	org.apache.commons.lang.text.StrBuilder:ensureCapacity:228	org.apache.commons.lang.text.StrBuilder:appendFixedWidthPadRight:1229	org.apache.commons.lang.text.StrBuilderTest:<init>:46	org.apache.commons.lang.text.StrBuilderTest:<init>:47	org.apache.commons.lang.text.StrBuilder:<init>:111	org.apache.commons.lang.text.StrBuilder:<init>:112	org.apache.commons.lang.text.StrBuilder:<init>:108	org.apache.commons.lang.text.StrBuilder:<init>:107

**Comment by jose** [comment]
Hi @nakhlarafi,

> Is there any way to get all the lines that were covered by a test case using gzoltar?

Yes, there is.  For your particular scenario you should look at three files produced by GZoltar:

- `tests.csv`: a list of all test cases (one per row) executed by GZoltar and its correspondent outcome (either PASS or FAIL), runtime in nanoseconds, and stacktrace (if it is a failing test case).
- `spectra.csv`: a list of all lines of code identified by GZoltar (one per row) of all classes under test. Each row follows the following format: `<class name>#<method name>(<method parameters>):<line number>`, e.g., `org.gzoltar.examples$CharacterCounter#processString(java.lang.String):37`.
- `matrix.txt`: a binary coverage matrix produced by GZoltar where each row represents the coverage of each individual test case and its outcome ("-" if the test case failed, "+" otherwise), and each column a line of code. 1 means that a test case covered a line of code, 0 otherwise.
Rows in the `matrix.txt` file follow the same order as rows in the `tests.csv` and columns in the `matrix.txt` file follow the same order as rows in the `spectra.csv`.

Parsing and combining the information in these three files will produce the information you're looking at.


--
Best,
Jose
