### ISSUE TITLE
Offline Instrumentation Error

### ISSUE THREAD

**Issue by kaiyuanw** [GZoltar/gzoltar#8]
### Context
I go to com.gzoltar.maven.examples/offline-instrumentation and run

`mvn clean test`

it fails with the following error

[ERROR] Failed to execute goal com.gzoltar:com.gzoltar.maven:1.7.2-SNAPSHOT:instrument (default-instrument) on project offline-instrumentation: [source error] no such class: com.gzoltar.internal.agent.rt.Offline -> [Help 1]

### GZoltar arguments
GZoltar maven plugin

### Expected behaviour
Expected to be run without any error

### Environment (please complete the following information, if relevant):
 - OS: Linux

**Comment by Derppening** [comment]
I have the same problem as well, and I could reproduce it with `gzoltarcli.jar`.

### Context
I was trying to use the instrumentation tool of GZoltar to generate a test class, and it thrown the same exception as above:
```
Exception in thread "main" com.gzoltar.internal.javassist.CannotCompileException: [source error] no such class: com.gzoltar.internal.agent.rt.Offline
```

### GZoltar arguments

```
java -jar gzoltarcli.jar instrument ../../build/classes/java/main/ --outputDirectory ../../gzoltarOutput
```

### Expected behaviour

Expected to run without error (as above).

### Environment (please complete the following information, if relevant):
 - OS: Linux
 - Version: 1.7.0 and 1.7.1

### Additional comments
For both tested versions, if I invoke GZoltar command-line specifying the main class, the issue will be resolved. 
```
java -cp gzoltaragent.jar:gzoltarant.jar:gzoltarcli.jar com.gzoltar.cli.Main instrument ../../build/classes/java/main/ --outputDirectory ../../gzoltarOutput
```
I suspect it might have to do with the Java CLASSPATH.
